### PR TITLE
Add OCaml r2pipe api

### PR DESCRIPTION
**Pull request by fxfactorial**

### CODE REVIEW

**Comment by Maijin** [comment]
@radare  btw, What happens if @fxfactorial is changing the content to something malicious ?

**Comment by fxfactorial** [comment]
It's the same as how the pip install was listed. Was that given similar questions?

**Comment by Maijin** [comment]
I'm not taking you as a specific case no worries :P just pointing this out

**Comment by fxfactorial** [comment]
Good point, appreciated

**Comment by radare** [comment]
What about pointing to the radare2-bindings repo? I would prefer to have all r2pipe bindings in 1 repo and point to external ones if needed

**Comment by XVilka** [comment]
@radare what about splitting r2pipe from conventional bindings repo?

**Comment by fxfactorial** [comment]
I really don't understand why all the bindings were dumped in radare itself. Each language has its own dependency issues, why make it a responsibility, monolithic in this repo itself.

**Comment by radare** [comment]
because you clone 1 repo or download 1 tarball and you get the bindings for all the languages in a shot, which is good for packaging, distributing and releasing. If i had to do a new release for every single binding every 6 weeks i will die (if im not already dying right now).

and yes. this will be moved to radare2-r2pipe repo after release. i promised this last time but r2con consumed me too much time and i was out of hands for doing more refactors and such.

about having everything in r2 github is for visibility, to allow everyone find the bindings in a single search and check examples from other languages in the same place.

**Comment by radare** [comment]
it is also good for having a single point of failure, so people can trust a single user instead of 20 separate repos, and for consistency, all bindings can be tested at once in a single place. to compare them and do changes in all of them in case of needed.

**Comment by radare** [comment]
also another ++ for having a single repo is for code review. much easier that way

**Comment by fxfactorial** [comment]
I see and understand your motivations, but each language has its own dependencies. This is like a standard library and I believe that standard libs are places where code goes to die. Now your repo "owns" the code, do you actively check if each binding is working? Do you have the domain knowledge of each language? Do you keep up with dependencies for each project? Does the Haskell binding still work? 

I think that projects should keep to their own purposes rather than consume other projects. If this viewpoint doesn't work, then feel free to close the PR and we can both move on; no hard feelings on my end. 

Insofar as visibility, you put it in the README and people can then download it correctly using the appropriate language's package manager.

**Comment by Maijin** [comment]
`Now your repo "owns" the code, do you actively check if each binding is working?`  -> radare2-extras travis is checking.
`Do you have the domain knowledge of each language? Do you keep up with dependencies for each project? And exactly, its not radare2's responsibility for the bindings to work, its up to the respective owners, Now they just dump it here and move on.`  -> Here I see a majour benefit on having it heresince having separated repo owned by separated user, it's even worse, since when they disappear it means a shitty version will always be up and can't be deleted and not updated whereas here we can update ourself, and yes you could still fork but people are lazy and always succeed to use the wrong version (see the amount of people using debian fork and complaining on #radare chan)

**Comment by Maijin** [comment]
IMHO it would be best to have separated repo but under radareorg or radare account tested a trigger every night on travis.

**Comment by radare** [comment]
i have commited your code into r2pipe/ocaml in r2b repo, with a ORIGIN file pointing to your repo, the pkg is compiled from your repo. which is ok for me.

i regluarly update the copies of external repos to have them updated in the release tarball, thats why there's a ORIGIN file. and yes there'r tests for some bindings, not all of them and they are not running on travis (yet)

i hate debian and im the first in pushing patches upstream to every single thing i found, as well as defined procedures for updating my forks of every external repo i use in r2, binutils capstone, sdb, grub, etc...

**Comment by Maijin** [comment]
@fxfactorial  You can help making travis-extras better too by fixing the builds for bindings and ensure the CI passes this way we can ensure no regressions. Only will remain to add a trigger every night or week

**Comment by Maijin** [comment]
https://travis-ci.org/radare/radare2-extras

**Comment by radare** [comment]
and no i dont know ocaml as well as you to maintain it by myself, i will like to be able, so having read your code is a nice way for learning, and you can always keep your fork and send pullreqs to the main repo like everyone does. but if not i will be syncing into my repo from now and then, so i dont see any issue in that procedure, you keep having the freedom to put the pkg pointing to your repo, you also have the freedom to do whatever you want in your code.

**Comment by fxfactorial** [comment]
@radare  @Maijin  Thank you

**Comment by radare** [comment]
the debian situation is a dead-end. i dont support or understand their burocracy, releasing or patching rules at all, all of those are totally different in netbsd's pkgsrc, where i've been contributing for a long time. Debian NEVER pushes aptches upstream, debian priorizes backporting instead of upgrading, debian applies several patches that are changing default behaviour of apps, etc... im totally against all those rules. and there's a newer pkg of r2 in debian, but it will hit stable in 2 years. so it will be always OLD.

**Comment by radare** [comment]
anyway thanks :D  we can keep discussing this somewhere else if you want

**Comment by radare** [comment]
here's another reason for having everything in the same repo: https://github.com/radare/radare2-bindings/pull/140

**Comment by radare** [comment]
could you pleaes work together and do a single implementation?

**Pull request merged**
