### PR TITLE
add lang-python3

### PR DESCRIPTION
**Pull request by Frefreak**
It would try to detect the existence of python-config for python3, exit if not found. User can also specify PYTHON_CONFIG env manually to specify it.

### CODE REVIEW

**Comment by Frefreak** [comment]
Sorry I don't quite get it... The binary name of python-config for py3 may be different on different system, the purpose of that `detect_pycfg3` is also to find the correct one to build python3. Do you mean those checks are unnecessary and should be removed? I was thinking user may actually install python2 version without these check.

**Comment by radare** [comment]
No i mean that python sucks. But those checks are necessary

**Comment by Frefreak** [comment]
lol. Should we do similar things to lang-python to make it python2 specific?

**Comment by radare** [comment]
yep that would be more consistent i think

thanks!

**Pull request merged**
